stages:
  - test

build and tests application:
  stage: test
  before_script:
    - echo "DEBUG=True" >> back/proj_back/.env
    - echo "SERVER_ORIGINS='127.0.0.1,localhost,iss-test-front,iss-front,iss-test-back,iss-back'" >> back/proj_back/.env
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml up -d --force-recreate
    - sleep 30
    # - docker logs iss-test-back
    # - docker exec iss-test-back ./manage.py test
    # - docker exec iss-test-front npm test
    # - docker exec iss-tests python3 test.py
    # - docker exec iss-tests flake8
    - docker exec iss-test-back ls
    - docker exec iss-test-back pwd
  after_script:
    - docker-compose -f docker-compose.test.yml down --volumes --remove-orphans
