stages:
  - tests

Test job:
  stage: tests
  before_script:
    - docker-compose
    - python3 --version
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose
  script:
    - echo "Setting environment up..."
    - cp back/proj_back/.env.sample back/proj_back/.env
    - echo "Starting docker test app..."
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml up -d
    - docker exec iss_test_back cat .env
  only:
    refs:
      - main
  when: manual