stages:
  - setup
setup-job:
  stage: setup
  script:
    - echo "Setting environment up..."
    - docker --version
    - python --version
    - pip --version
  only:
    refs:
      - main
  when: manual