stages:
  - setup
  - startup
  - runtests

setup-job:
  stage: setup
  script:
    - echo "Setting environment up..."
    - pwd
    - cat {id_iss,id_iss.pub} > v.txt
    - rm v.txt
    - git clone git@gitlab.iss.ru:m-zyuzin/data-collection-app.git
    - cp data-collection-app/back/proj_back/.env.sample  data-collection-app/back/proj_back/.env
    - cat data-collection-app/back/proj_back/.env
  only:
    refs:
      - main
  when: manual

startup-job:
  stage: startup
  script:
    - echo "Starting docker test app..."
    - docker compose -f data-collection-app/docker-compose.test.yml -d
    - docker exec iss_test_back cat .env
  only:
    refs:
      - main
  when: manual

test-job:
  stage: runtests
  script: echo 'RUN TESTS'
  only:
    refs:
      - main
  when: manual