stages:
  - test

build and tests application:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml up -d --force-recreate
    - sleep 30
    - docker exec iss-test-front npm lint
    - docker exec iss-tests flake8
    - docker exec iss-test-front npm test
    - docker exec iss-test-front npm compile
    - docker exec iss-test-back ./manage.py test
    - docker exec iss-test-storage python3 src/test.py
    # - docker exec iss-tests python3 test.py
  after_script:
    - docker-compose -f docker-compose.test.yml down --volumes --remove-orphans
