stages:
  - tests

Tests setup:
  stage: tests
  services:
    - docker:dind
  script:
    - docker info
    - python3 --version
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose
    - echo "Setting environment up..."
    - cp back/proj_back/.env.sample back/proj_back/.env
  only:
    refs:
      - main
  when: manual

Tests boot up:
  stage: tests
  script:
    - echo "Starting docker test app..."
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml up -d
    - docker exec iss_test_back cat .env
  needs:
    - job: Tests setup
  only:
    refs:
      - main


