services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: iss_app_db
      POSTGRES_HOST_AUTH_METHOD: trust  
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
