version: "3.8"

services:
  iss-back:
    volumes:
      - ./backend-app:/app

  iss-storage:
    volumes:
      - ./storage-app/src:/app/src

  iss-front:
    volumes:
      - ./frontend-app/src:/app/src
      - ./frontend-app/public:/app/public
    command: npm start

  iss-worker:
    volumes:
      - ./storage-app/src:/app/src

  dashboard:
    container_name: iss_dashboard
    build:
      dockerfile: Dockerfile.storage
    ports:
      - 9090:5555
    environment:
      CELERY_BROKER_URL: redis://iss-broker:6379/0
      CELERY_RESULT_BACKEND: redis://iss-broker:6379/0
    restart: always
    depends_on:
      - iss-broker
      - iss-worker
    command: celery --broker=redis://iss-broker:6379/0 flower --port=5555
    networks:
      - iss_network

networks:
  iss_network:
