FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
        postgresql-client \
        gcc \
        python3-dev \
        musl-dev \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./backend-app/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend-app ./