version: "3.8"

services:
  iss_db:
    container_name: iss_db
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: iss_app_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - iss_network

  iss_back:
    container_name: iss_back
    image: iss_back
    build: ./back
    restart: always
    environment:
      DB_HOST: iss_db
      DB_NAME: iss_app_db
      FRONTEND_EXT_PORT: 3000
    depends_on:
      - iss_db
    volumes:
      - ./back/proj_back:/app
    command: >
      sh -c "python manage.py makemigrations user &&
             python manage.py makemigrations project &&
             python manage.py makemigrations attribute &&
             python manage.py makemigrations file &&
             python manage.py migrate &&
             gunicorn --config './conf/gunicorn_conf.py' proj_back.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - iss_network

  iss_front:
    container_name: iss_front
    image: iss_front
    build: ./front
    restart: always
    environment:
      - PORT=3001
    depends_on:
      - iss_back
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    command: npm start
    networks:
      - iss_network

  iss_proxy:
    container_name: iss_proxy
    image: nginx:1.25.1-alpine
    depends_on:
      - iss_front
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - iss_network

networks:
  iss_network:
