FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

WORKDIR /tests

COPY ./tests/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./tests ./

COPY ./back/proj_back ./backend_code