FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

RUN addgroup --system iss && adduser --system --group iss

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
        python3-dev \
        musl-dev \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./storage-app/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./storage-app/src ./src

RUN chown -R iss:iss /app
