version: "3.8"

services:
  iss-test-db:
    container_name: iss-test-db
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: iss_test_app_db
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - iss_test_network

  iss-test-back:
    container_name: iss-test-back
    image: iss_back
    build: ./back
    restart: always
    depends_on:
      - iss-test-db
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DB_HOST: iss-test-db
      DB_NAME: iss_test_app_db
      CASE: test
    command: >
      sh -c "python manage.py makemigrations user &&
             python manage.py makemigrations project &&
             python manage.py makemigrations attribute &&
             python manage.py makemigrations file &&
             python manage.py migrate &&
             python manage.py createsuperuser --email=admin@example.ex --noinput &&
             gunicorn --config './conf/gunicorn_conf.py' proj_back.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - iss_test_network

  iss-test-front:
    container_name: iss-test-front
    image: iss_front
    build: ./front
    restart: always
    depends_on:
      - iss-test-back
    environment:
      CASE: test
      CI: true
    command: npm start
    networks:
      - iss_test_network

  iss-selenium-hub:
    container_name: iss-selenium-hub
    # image: selenium/hub
    image: seleniarm/hub
    depends_on:
      - iss-test-front
    networks:
      - iss_test_network

  # iss-selenium-chrome:
  #   container_name: iss-selenium-chrome
  #   image: selenium/node-chrome
  #   depends_on:
  #     - iss-selenium-hub
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   environment:
  #     SE_EVENT_BUS_HOST: iss-selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #   networks:
  #     - iss_test_network

  # iss-selenium-edge:
  #   container_name: iss-selenium-edge
  #   image: selenium/node-edge
  #   depends_on:
  #     - iss-selenium-hub
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   environment:
  #     SE_EVENT_BUS_HOST: iss-selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #   networks:
  #     - iss_test_network

  iss-selenium-fox:
    container_name: iss-selenium-fox
    # image: selenium/node-firefox
    image: seleniarm/node-firefox
    depends_on:
      - iss-selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      SE_EVENT_BUS_HOST: iss-selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    networks:
      - iss_test_network

  iss-test-ui:
    container_name: iss-test-ui
    build: ./ui-tests
    depends_on:
      # - iss-selenium-chrome
      # - iss-selenium-edge
      - iss-selenium-fox
    command: tail -f /dev/null
    networks:
      - iss_test_network


networks:
  iss_test_network:
