from .attribute_tests.models_test import AttributeModelsTest
from .attribute_tests.serializers_test import AttributeSerializersTest
from .attribute_tests.services_test import CheckServiceTest, DeleteServiceTest
from .attribute_tests.views_test import LevelViewsetTest, AttributeViewsetTest
from .attribute_tests.permissions_test import LevelPermissionTest, AttributePermissionTest
