name: Tests CI

on:
  workflow_dispatch:
  # push:
  #   branches-ignore:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Images
        run: docker-compose -f docker-compose.test.yml build

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.test.yml up -d --force-recreate
          sleep 30
          docker exec iss-test-front npm lint
          docker exec iss-tests flake8
          docker exec iss-test-front npm test
          # docker exec iss-test-front npm compile
          docker exec iss-test-back ./manage.py test
          docker exec iss-test-storage python3 src/test.py
          # docker exec iss-tests python3 test.py

      - name: Clean up
        run: docker-compose -f docker-compose.test.yml down --volumes --remove-orphans
